apiVersion: k8s.nginx.org/v1alpha1
kind: NginxIngressController
metadata:
  name: nginx-op-test
  namespace: nginx-op-test-ns
spec:
  type: deployment
  nginxPlus: false
  image:
    repository: registry.hub.docker.com/nginx/nginx-ingress
    tag: edge-ubi
    pullPolicy: Always
  replicas: 1
  ingressClass: nginx-op-test
  serviceType: LoadBalancer
  enableCRDs: false