apiVersion: k8s.nginx.org/v1alpha1
kind: NginxIngressController
metadata:
  name: nginx-op-test
  namespace: default
spec:
  type: deployment
  nginxPlus: false
  image:
    repository: registry.hub.docker.com/nginx/nginx-ingress
    tag: 1.9.1-ubi
    pullPolicy: Always
  replicas: 1
  ingressClass: nginx-op-test
  useIngressClassOnly: true
  serviceType: LoadBalancer
  enableCRDs: true