apiVersion: k8s.nginx.org/v1alpha1
kind: NginxIngressController
metadata:
  name: nginx-op-test-ingress-controller
  namespace: default
spec:
  type: daemonset
  nginxPlus: false
  image:
    repository: registry.hub.docker.com/nginx/nginx-ingress
    tag: 1.9.1-ubi
    pullPolicy: Always
  ingressClass: nginx-op-test-ingress
  useIngressClassOnly: true
  serviceType: LoadBalancer
  enableCRDs: false