apiVersion: v1
kind: Service
metadata:
  name: nginx3
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress3
  annotations:
    kubernetes.io/ingress.class: "nginx-test3"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx3
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment3
spec:
  selector:
    matchLabels:
      app: nginx3
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx3
    spec:
      containers:
      - name: nginx3
        image: nginx:1.19.6
        ports:
        - containerPort: 80