apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.spec.name }}-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ .Values.spec.name }}-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.spec.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ index .Values "ingress-nginx" "controller" "ingressClass" }}
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.spec.name }}-service
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.spec.name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.spec.name }}-app
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.spec.name }}-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.6
        ports:
        - containerPort: 80